repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version available
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ".*templates/.*.yaml$"  # exclude helm templates
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1  # Use the latest version available
    hooks:
      - id: mypy
        additional_dependencies: [types-ujson==5.10.0.20240515, types-simplejson==3.20.0.20250218, types-requests, types-tabulate==0.9.0.20241207]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.1
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix, --exit-non-zero-on-fix, --extend-select=ANN20, --extend-select=ANN001 ]
    - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.17 # Use the latest version available
    hooks:
      - id: uv-export
